<?php

class FAQ extends ObjectModel
{
    public $id_faq;
    public $question;
    public $answer;
    public $friendly_url;
    public $active;
    public $associated_products;

    public static $definition = array(
        'table' => 'faqs',
        'primary' => 'id_faq',
        'multilang' => true,
        'fields' => array(
            'question' => array('type' => self::TYPE_STRING, 'lang' => true, 'required' => true),
            'answer' => array('type' => self::TYPE_STRING, 'lang' => true),
            'friendly_url' => array('type' => self::TYPE_STRING, 'required' => true),
            'active' => array('type' => self::TYPE_BOOL),
            'associated_products' => array('type' => self::TYPE_STRING)
        )
    );

    public function add($auto_date = true, $null_values = false)
    {

        $this->associated_products = serialize($this->associated_products);

        return parent::add($auto_date, $null_values); // TODO: Change the autogenerated stub

    }

    public function update($null_values = false)
    {
        $this->associated_products = serialize($this->associated_products);

        return parent::update($null_values); // TODO: Change the autogenerated stub
    }

}