<?php

require_once(dirname(__FILE__) . '/../../classes/FAQ.php');

class faqmoduleDisplayfaqsModuleFrontController extends ModuleFrontControllerCore
{
    public function __construct()
    {
        parent::__construct();
        $this->module = new FaqModule();
        $this->model = new PrestaShopCollection('FAQ');
        $this->objectmodel = new FAQ();
        $this->display_column_left = false;
    }

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub

        if (Tools::getValue('friendly_url') !== 'all') {
            $this->show();
        } else {
            $this->index();
        }
    }

    public function displayAjax()
    {
        $this->add();
    }

    public function index()
    {
        $all_faqs = $this->model->getResults();
        $this->context->smarty->assign(
            array(
                'all_faqs' => $all_faqs
            )
        );

        $this->setTemplate('faq_index.tpl');
    }

    public function show()
    {
        $chosen_faq = $this->model->where('friendly_url', '=', Tools::getValue('friendly_url'))->getResults();
        $this->context->smarty->assign(
            array(
                'chosen_faq' => $chosen_faq
            )
        );

        $this->setTemplate('faq_show.tpl');
    }

    public function add()
    {
        $this->objectmodel->question[1] = Tools::getValue('question');
        $this->objectmodel->associated_products[] = Tools::getValue('id_product');
        if ($this->objectmodel->add()) {
            die(json_encode('Success'));
        } else {
            die(json_encode('Error'));
        }
    }
}
