<?php

require_once (__DIR__ . '/../../classes/FAQ.php');

class faqmoduleDisplayfaqsModuleFrontController extends ModuleFrontControllerCore
{
    public function __construct()
    {
        $this->module = new FaqModule();
        $this->model = new PrestaShopCollection('FAQ');
        $this->objectmodel = new FAQ();
        $this->display_column_left = false;
        parent::__construct();
    }

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub

        if (Tools::getValue('friendly_url') !== 'all') {
            $chosen_faq = $this->model->where('friendly_url', '=', Tools::getValue('friendly_url'))->getResults();
            $this->context->smarty->assign(
                array(
                    'chosen_faq' => $chosen_faq
                )
            );

            $this->setTemplate('faq_show.tpl');
        } else {
            $all_faqs = $this->model->getResults();
            $this->context->smarty->assign(
                array(
                    'all_faqs' => $all_faqs
                )
            );

            $this->setTemplate('faq_index.tpl');
        }
    }


    public function displayAjax()
    {

        $this->objectmodel->question[1] = Tools::getValue('question');
        $this->objectmodel->associated_products[] = Tools::getValue('id_product');
        if(!$this->objectmodel->add()) {
            return 'ERROR';
        }

        die($this->context->smarty->fetch(__DIR__ . '/../../views/templates/hook/product.tpl'));
    }
}